turbine:
  combine-host-port: true
  aggregator:
    cluster-config: default # 指定聚合哪些集群，多个使用","分割，默认为default。
  #turbine.app-config: 配置监控服务的列表，表明监控哪些服务多个使用","分割
  # 配置Eureka中的serviceId列表，表明监控哪些服务
  app-config: gateway-server,demo-provider,demo-customer

  #更改turbine连接的默认uri ,默认为/actuator/hystrix.stream
  #turbine.cluster-name-expression: 用于指定集群名称，当服务数量非常多的时候，
  #可以启动多个Turbine服务来构建不同的聚合集群，而该参数可以用来区分这些不同的聚合集群，
  #同时该参数值可以再Hystrix仪表盘中用来定位不同的聚合集群，metadata['cluster']
  cluster-name-expression: new String("default")
  instanceUrlSuffix: /hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: '*'
  eureka:
    server:
      # 测试时关闭自我保护机制，保证不可用服务及时踢出
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 60000  #清理间隔（毫秒）
      #peerNodeReadTimeoutMs: 200000
      #peerNodeConnectTimeoutMs: 60000
      #https://blog.csdn.net/qq_26440803/article/details/83113037
    instance:
      hostname: localhost
      prefer-ip-address: true
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port} #指定实例id
      lease-expiration-duration-in-seconds: 30   #续约更新时间间隔
      lease-renewal-interval-in-seconds: 10     #续约到期时间间隔，默认90
      leaseRenewalIntervalInSeconds: 10     #心跳时间
    client:
      registerWithEureka: true  #是否注册自己到eureka服务中，默认不注册
      fetchRegistry: true     #是否从eureka服务中获取注册信息
      serviceUrl:
        # 服务器注册/获取服务器的zone
        #自己注册到eureka那个服务,可注册多个，用，分隔
        defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      eurekaServerConnectTimeoutSeconds: 60
      eurekaServerReadTimeoutSeconds: 60
      # 健康检测问题 https://my.oschina.net/andChow/blog/1939238
      healthcheck:
        enabled: false
        # 如下配置则打开db-health检查
          #db:
           # enabled: true

server:
  port: 7002

spring:
  application:
    name: api-turbine
  #security:
   # sessions: stateless
    #basic:
     # enabled: true #启用SpringSecurity的安全配置
    #user:
     #  name: admin #认证用户名
      # password: admin # 认证密码
       #role:  # 授权角色
       #- USER