server:
  port: 8081
  #servlet:
   #  context-path: /ddemo  #默认没有项目名，你可以加
spring:
  application:
    name: demo-customer

eureka:
  #eueka 主机名
  instance:
    hostname: localhost
  client:
    #提供者和消费者的注册地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
  hystrix:
    enabled: true